#!/usr/bin/env bash
# configure ufw to allow only SSH, HTTP, HTTPS

echo -e "Updating\n"
sudo apt-get update -y

echo -e "Installing UFW\n"
sudo apt-get install -y ufw

echo -e "configuring UFW...\n"

# Allow Outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# Enable Firewall (--force skips the interactive y/n confirmation prompt)
sudo ufw --force enable

echo -e "Process Completed.\n"
