#!/usr/bin/env bash
# Creating a server with a redirect

# Updating all packages
sudo apt-get update -y && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y
sudo sed -i "/server_name _;/a\\
    location /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
    }" /etc/nginx/sites-available/default

# Reload nginx
sudo service nginx restart
