#!/usr/bin/env bash
# Creating a server with a redirect

# Updating all packages
sudo apt-get update -y && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y


# Creating a 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/listen 80 default_server;/a\
        error_page 404 /404.html;' /etc/nginx/sites-available/default

# Reload nginx
sudo service nginx restart
